const employeeTypes = {
    TOGGLE : 'EMPLOYEE ADD DATA',
    CHANGE_DATA: 'EMPLOYEE CHANGE DATA',
    SUBMIT_DATA: 'EMPLOYEE SUBMIT DATA',
    DELETE_DATA : 'EMPLOYEE DELETE DATA',
    GET_DATA: 'EMPLOYEE GET DATA',
    GET_DOCUMENT_TYPE: 'EMPLOYEE DOCUMENT TYPE',
    GET_LIST_FILE: "EMPLOYEE LIST FILE",
    GET_FILE: 'EMPLOYEE GET FILE',
    RESET_FORM: 'EMPOYEE RESET FORM'
}

export default employeeTypes;